POST http://localhost:8000/event_types HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTY1MjMxNTMsInVzZXJJZCI6IjdiZDk3MDE0LWI0ZmItNDFjNS04ZjY4LTc3MmViN2FiYWVmMyJ9.sNwU2Td10qqsI5vkKp49Vn6ZdhB1I9Ma-pMkqoUADNQ

{
    "code":"LIN",
    "description":"Login"
}

###

DELETE http://localhost:8000/event_types/IDDD HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/event_types/IDDD HTTP/1.1
Content-Type: application/json

{
    "code":"LIN",
    "description":"Log-in"
}
###

GET http://localhost:8000/event_types/IDDD HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTU1Njk3NjQsInVzZXJJZCI6IjdiZDk3MDE0LWI0ZmItNDFjNS04ZjY4LTc3MmViN2FiYWVmMyJ9.eto8J4ZN7HHqNOE_3YT7_X9KKKaUUbsIDFTyv0-kIIw

###

GET http://localhost:8000/event_types HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTY1MjMxNTMsInVzZXJJZCI6IjdiZDk3MDE0LWI0ZmItNDFjNS04ZjY4LTc3MmViN2FiYWVmMyJ9.sNwU2Td10qqsI5vkKp49Vn6ZdhB1I9Ma-pMkqoUADNQ
