# Etapa 1: build da aplicação
FROM golang:1.24.3 AS builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app

# Etapa 2: imagem final
FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/app .

# Porta que a aplicação expõe
EXPOSE 8080

CMD ["./app"]
