// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          string
	CreatedAt   time.Time
	UserID      string
	EventTypeID string
}

type EventType struct {
	ID          string
	Code        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
